# -------------------------
# Builder stage
# -------------------------
FROM python:slim-trixie AS builder

# Install required tools
RUN apt update && apt install -y curl ca-certificates

# Install Poetry into /etc/poetry (includes its own musl Python)
RUN curl -sSL https://install.python-poetry.org | \
    POETRY_HOME=/etc/poetry python3 -

# -------------------------
# Final stage
# -------------------------
FROM python:slim-trixie

# Install git
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        git \
        ca-certificates
RUN rm -rf \
      /usr/share/doc/* \
      /usr/share/man/* \
      /usr/share/locale/* \
      /usr/share/info/* \
      /var/lib/apt/lists/*

# Copy Poetry from builder
COPY --from=builder /etc/poetry /etc/poetry

# Make poetry available on PATH
RUN ln -s /etc/poetry/venv/bin/poetry /usr/local/bin/poetry

# Optional sanity check
RUN /usr/local/bin/poetry --version

# Copy entrypoint
COPY scripts/entrypoint.debian /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# ENTRYPOINT handles switching to host UID/GID
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Default command: open a shell
CMD ["/bin/bash"]